### ISSUE TITLE
yacy  uses nonfree-Javascript

### ISSUE THREAD

**Issue by darkneptune** [yacy/yacy_search_server#136]
Please make your JavaScript free.

I could not completely use the 'yacy' site (http://localhost:8090/index.html) because it requires running JavaScript code which is not free software.  Since a nonfree program disrespects the user's freedom, I decided not to run it. 

See http://gnu.org/philosophy/javascript-trap.html for more information, and please make your JavaScript code free.

Thanks.

Browser extension used: GNU LibreJS.

- List of blocked JavaScript:

  NONTRIVIAL: eval has been found in code
http://localhost:8090/env/bootstrap/js/bootstrap.min.js

  NONTRIVIAL: Creates an xhr object
http://localhost:8090/env/bootstrap/js/jquery.min.js

**Comment by sinkuu** [comment]
Both libraries are licenced under MIT License. LibreJS will happily load them if loaded from [a known CDN](https://bzr.savannah.gnu.org/lh/librejs/dev/annotate/head:/data/script_libraries/script-libraries.json).

**Comment by Scarfmonster** [comment]
The only solution here is to whitelist your YaCy server. I don't think loading the libraries from a public CDN is a good idea because then it would be impossible to run YaCy on an isolated network, and anyway not everyone may wish to broadcast their use of YaCy to the public, nevermind that it's dubious from the security/privacy perspective.

**Comment by luccioman** [comment]
I also agree that using a CDN is not a good idea in the context of YaCy : even considering only the performances aspect, for the people running YaCy server and browser run on the same computer it doesn't make sense to fetch resources on a remote CDN that are already available locally.

About LibreJS : since PR #56 , YaCy is configured to be LibreJS friendly, either by providing explicit license information for inline JavaScript, or by listing infos in a /jslicense.html page for separated JS files. So you should even not need to whitelist your server.
For example on Debian Stretch, with Firefox ESR 52.4.0 and LibresJS 6.0.13 enabled, I see all scripts marked as "Accepted" by LibreJs when browsing 1.921/9447 or 1.92/9000 YaCy peers.

@darkneptune what are your exact browser and LibreJs versions?

**Comment by darkneptune** [comment]
JS problem detected by LibreJS into:

Iceweasel 1:56.0.2-1 = 0 

Icecat 52.3.0_gnu1-2 = 2

**Comment by luccioman** [comment]
That's strange, I do not reproduce the issue with IceCat 52.3.0 on Debian Stretch, browsing either a YaCy 1.92/9000 or 1.921/9447.
@darkneptune is it the Parabola IceCat package that your run? Do you get blocked scripts once opening YaCy index page, or search results, or a specific admin page?

**Comment by darkneptune** [comment]
Yes, I run Parabola Icecat package: 52.3.0_gnu1-2

Here there is a screenshot.
![ccc](https://user-images.githubusercontent.com/6899871/32610438-14989ee8-c563-11e7-88ea-8c2b93af533c.png)

**Comment by luccioman** [comment]
Ok I just ran again Parabola live from the ISO parabola-openrc-lxde-2017.11.05-dual.iso, installed the provided yacy and icecat packages... but it sill works fine for me : no Blocked JavaScript at all when opening with IceCat the YaCy local peer index page, or the one from another remote peer.
I suspect this reveals some bug in the LibreJs plugin.
Do you get the same reports if you open the index page of some other peers (running 1.92/9000 or more recent) listed in one of the /Network.html page tabs?

**Comment by darkneptune** [comment]
I start 'yacy' running: 'sudo /opt/yacy/yacy start'

Then, a new GNU Icecat Windows pop-ups with yacy page on it. There is where LibreJS detects bad JS. And into the other yacy configuration pages.

But if I open 'yacy web page' from another Icecat instance, no dab JS is detected. :/

**Comment by luccioman** [comment]
I wonder what kind of specific settings causes this difference of behaviour. I tested again to have the most possible similar scenario as yours : Parabola packages update, then installation of IceCat defined as the preferred browser, then installation of YaCy and jdk7-openjdk, and start of YaCy automatically opening IceCat... but still no "luck" to reproduce the issue : no YaCy JavaScript appears as blocked, although LibreJS is enabled.

Maybe you would like to take some time to check with a more recent version of YaCy, for example using a binary release from http://kaskelix.de/update/ (the latest one is yacy_v1.921_20170830_9342.tar.gz)
, or building from latest sources?

**Comment by darkneptune** [comment]
ok. forget it. maybe is a Icecat bug...

Thanks,
