### ISSUE TITLE
Starting a crawl kills any in-progress JavaScript sorting

### ISSUE THREAD

**Issue by JeremyRand** [yacy/yacy_search_server#156]
# YaCy version

yacy_v1.921_20180120_9537.tar.gz

# Steps to reproduce

1. Enable JavaScript sorting.
2. Perform a search.
3. While the results are still loading, start a YaCy crawl in another tab.

# Expected results

The search should be unaffected.

# Observed results

The search immediately stops loading results.

**Comment by luccioman** [comment]
This is because when a new crawl is started the search event cache is cleaned up (see [Crawler_p.java](https://github.com/yacy/yacy_search_server/blob/8d7099a081eb381a39fc5feb301583b827a97f37/htroot/Crawler_p.java#L88) ).
But this is not the only case, there are quite a few other places where the search event cache is cleaned up, notably on admin operations.

Is it really a problem? You just have to click the "Search again" button, and the JS resorted search run fine again while the crawl is running.

**Comment by JeremyRand** [comment]
@luccioman Thanks, that fixed it.

FYI my use case here was that I'm working on a WebExtension that crawls with YaCy the top 100 Google and DuckDuckGo results for a query whenever you do a YaCy search.  Which has the side effect that, a few milliseconds after the YaCy search results page loads, a crawl gets started (so, before your fix, no search results would ever display).
