### ISSUE TITLE
Can't add Boost Functions

### ISSUE THREAD

**Issue by Marx1st** [yacy/yacy_search_server#169]
Hi,

I'm running YaCy version: 1.921/9598 and I want to test some boost functions. The problem is, I can't add any. Even when I add the example "recip(ms(NOW,last_modified),3.16e-11,1,1)" as soon as I press "Set Boost Function", the text area is empty again.

Tobias

**Comment by luccioman** [comment]
Hi @Marx1st , your custom boost function is indeed well recorded, but since this [patch](https://github.com/yacy/yacy_search_server/commit/5f706797cbda086a9fbfde73d3f1ed4b2cf523d2), as soon as your function contains the string `last_modified`, it is ignored and considered empty.

The patch is a bit rude (a more proper and user-friendly fix would help here) and the provided example in the page should be consequently updated.

But at least for now you know that you can test boost functions... on any other field than the `last_modified` one...

**Comment by luccioman** [comment]
@Marx1st , if you wish to update to latest sources from GitHub, this issue is now fixed.
