### ISSUE TITLE
Client can't execute: Received fatal alert: handshake_failure duration

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#189]
Hi,

I can't crawl blenderartists.org - I compiled the latest version 1.921/9732
on Ubuntu with jdk 1.8.

> Crawling of "https://blenderartists.org/" failed. Reason: scraper cannot load URL: Client can't execute: Received fatal alert: handshake_failure duration=442 for url https://blenderartists.org//

**Comment by luccioman** [comment]
Hi @songproducer , this error is caused when [SNI - Server Name Indication](https://tools.ietf.org/html/rfc6066#section-3) extension is disabled.

Currently, YaCy launch scripts are indeed configured to disable SNI extension. This is a trade-off : some websites have improper TLS configuration, and crawling them on https with SNI extension enabled would fail due to the way Java Security internally handles this. On the other hand, without SNI extension enabled, you can not crawl some https websites such as blenderartists.org.
Unfortunately this setting can not be set at runtime, for example in crawl configuration settings.

So if you want to be able to crawl https://blenderartists.org, you have to edit your YaCy launch script, likely startYACY.sh if you are using it on Ubuntu, and change the option `-Djsse.enableSNIExtension=false` to `-Djsse.enableSNIExtension=true`. And then restart your YaCy server and retry the crawl.

**Comment by songproducer** [comment]
@luccioman thanks very much!
