### ISSUE TITLE
Can't delete vocabularies fully

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#206]
I created some vocabularies through Vocabulary_p.html
but even though I deleted them on that page, they still show up on RankingSolr_p.html under the Boost Query section.

How can I fully remove them?

**Comment by luccioman** [comment]
@songproducer , if these vocabulary names still appear in the RankingSolr_p.html page, it is because some documents in your Solr index still reference them.
So if you want everything to be clean, you have to recrawl these documents. You can use for that the Field Re-Indexing admin page (at /IndexReIndexMonitor_p.html), and type for example `vocabularies_sxt:your_vocabulary_name` in the "Solr query", eventually check what is selected, and then start the job using the "start recrawl job now" button.

**Comment by songproducer** [comment]
Thanks!
