### ISSUE TITLE
What do the bookmark, recommend, and delete buttons do?

### ISSUE THREAD

**Issue by edom** [yacy/yacy_search_server#213]
Those are the buttons beside a search result entry.

What do they do, especially the recommend and the delete buttons?

**Comment by uzerus** [comment]
When you bookmark a result, net time you search the same keyword it will be at top of other results (or i am wrong)

By the way how the search results are sorted? popularity

+1

**Comment by edom** [comment]
Does clicking any of those buttons affect only my YaCy instance, or does it also affect all YaCy peers?

(If anyone can explain those buttons, I'm willing to improve those buttons' tooltips in the web application.)

**Comment by luccioman** [comment]
Hi @edom , some details about the buttons :
 - bookmark : add the URL to your YaCy peer bookmarks. The list is visible at the /Bookmarks.html page. This does not affect the ranking of next search requests.
 - recommand : this creates a recommendation message to the YaCy network, that will be visible by other peers in their /Surftips.html page.
 - delete : this deletes the URL from your own local index. This does not affect other peers indexes, but will only send a negative vote message visible in their /Surftips.html page.

**Comment by edom** [comment]
Hi @luccioman , thanks for the answer.

I was expecting a link to Bookmarks.html on the Administration sidebar, but I couldn't find it. Did I overlook it, or it just isn't there? I'm compiling YaCy from source (master branch, yesterday). If you hadn't answered, I would have never found that page. Is it OK if I add a link to Bookmarks.html on the sidebar?

Do the votes affect YaCy (are the votes for machine consumption), or are the votes for human consumption?

Here are what I infer/guess from your replies and from the YaCy user interface. Please correct my wrong thoughts.

* "Recommend" affects remote crawling.
* "Recommend" doesn't affect ranking.
* Suppose we search query Q. Suppose we get a result R from another peer. Suppose we "delete" R. Then R may appear again if we repeat the search Q later.

Thank you.

**Comment by luccioman** [comment]
That's true that there is no more link to the Bookmarks.html page, since some years now (commit 5ea5bb3). I don't know if this was intentional or a mistake. Maybe @Orbiter or @reger24 could clarify about this?
What's more, to my mind this would probably be more usable to link to the Bookmarks.html page in "add" mode with full edition options in a new tab from search results, rather than silently bookmarking and reloading the results page as does the current button.

"Votes" (through recommendation or deletion) are only propagated to others peers through the news mechanism, so it is primarily only for human consumption through the Surftips.html page. It does not affect ranking at all. But you could eventually process it with external tools using the News.rss feed.

> "Recommend" affects remote crawling.

Not as far as I know. Remote crawling is controlled through the /RemoteCrawl_p.html page and on crawl starts.


> "Recommend" doesn't affect ranking.

Right

> Suppose we search query Q. Suppose we get a result R from another peer. Suppose we "delete" R. Then R may appear again if we repeat the search Q later.

Right. This makes this button of limited usefulness to my mind. Personally I would prefer a delete and blacklist button.

**Comment by edom** [comment]
> Personally I would prefer a delete and blacklist button.

That would be nice. There are indeed "delete and blacklist" buttons in the pages `CrawlResults.html?process=5` and `CrawlResults.html?process=6`, but unfortunately these buttons work with crawl results, not search results.
