### ISSUE TITLE
Seed upload returns 404 response code

### ISSUE THREAD

**Issue by vikulin** [yacy/yacy_search_server#227]
Yacy saves a seed file as a tmp file with random id seedFile5713919420317036537.txt. This leads 404 response code.

**Comment by vikulin** [comment]
Related code:
https://github.com/yacy/yacy_search_server/blob/e97580dfc713d7572dd95c3f4d4cc19a2d46b6a2/source/net/yacy/peers/SeedDB.java#L862

**Comment by vikulin** [comment]
Found a workaround:
Run sh script for the folder where the seed file will be saved:
inotifywait -r -m -e modify ROOT | 
   while read path _ file; do 
       echo $path$file modified
       cd $path && mv $file seed.txt
   done
Run SCP seed upload. THe scrip[t automatically changes seed file name to correct seed.txt on fly. as result server does not return 404 and seed.txt becomes available.
F e:
https://[fc3b:48f8:c281:a358:4b41:73d:c941:3ff0]:8443/seed.txt

**Comment by vikulin** [comment]
Used SCP method. Random tmp file name is an issue because user can't forecast what file name is going to be created next time.

**Comment by luccioman** [comment]
Ok @vikulin thanks for the details.
But to my mind the seed copy file was designed to be a temporary file used only in the seed upload process (it is deleted at the end). If you want to rely on a stable file name with up to date data for any external tooling, I think you should rather use the DATA/INDEX/<network>/NETWORK/mySeed.txt file.

**Comment by luccioman** [comment]
@vikulin I may have misunderstood your use case : for the remote scp target path, did you specified a directory or a file path?

**Comment by vikulin** [comment]
Yes, I did

пт, 14 сент. 2018 г. в 10:30, luccioman <notifications@github.com>:

**Comment by vikulin** [comment]
>But to my mind the seed copy file was designed to be a temporary file used
only in the seed upload process (it is deleted at the end)
What is the purpose to create a temporal seed file if it won't be used by
any other nodes or even by the host itself?

пт, 14 сент. 2018 г. в 10:42, Vadym Vikulin <vadym.vikulin@gmail.com>:

**Comment by luccioman** [comment]
I think the only purpose of the temporary file is to provide a local input file for the upload process, for example to feed the scp command.

By the way, with the current implementation, doesn't it work better for you if you enter the file name in the remote target path (such as `/your_target_folder/seed.txt`)?

**Comment by vikulin** [comment]
Excatly, yacy seed configuration page expects seed.txt file and can not
find it.

пт, 14 сент. 2018 г. в 14:44, luccioman <notifications@github.com>:

**Comment by luccioman** [comment]
@vikulin I mean in the `Uploading via SCP:` section, in the field "Path: ", you have to enter something like `/var/www/seed.txt` instead of `/var/www`. By doing that way, the file is effectively written remotely to `/var/www/seed.txt`, whatever is the local origin file name.
If you enter only a directory path like `/var/www`, that's right that currently the origin file name is written remotely to something like `/var/www/seedFile1895254696984057584.txt`.

**Comment by vikulin** [comment]
No, I have entered correct /usr/apache-tomcat-8.5.33/webapps/ROOT.

Again and last time: yacy seed config page expectes seed.txt instead of
seedFilexxxxxxx.txt. This is why it returns 404.

сб, 15 сент. 2018 г. в 11:44, luccioman <notifications@github.com>:

**Comment by luccioman** [comment]
Why don't you try with the path `/usr/apache-tomcat-8.5.33/webapps/ROOT/seed.txt` instead? `/usr/apache-tomcat-8.5.33/webapps/ROOT` is a directory/folder path.

I just tested with a remote Apache httpd (instead of tomcat, but this is the same principle) and it worked properly.

You can also read again the help message of the field that states : "The remote path on the server, like '~/yacy/seed.txt'"

**Comment by luccioman** [comment]
An now with commit 2a73b63, the default scp target file name will be constant.

**Comment by vikulin** [comment]
Thanks. This is exctly what I expected to be fixed.

**Comment by luccioman** [comment]
Fix embedded in developer release 1.921/9788
