### ISSUE TITLE
"undefined" title in crawl log

### ISSUE THREAD

**Issue by Vort** [yacy/yacy_search_server#244]
When crawler hits the page with dot in title, title in crawl log becomes "undefined". Look at screenshot:
![yacycld](https://user-images.githubusercontent.com/1242858/46719705-4aa06400-cc77-11e8-92d8-78184db59352.png)

Version: 1.921_20181008_9798

**Comment by luccioman** [comment]
Thanks for your report @Vort .
Indeed the problem is deeper than a simple issue with the title : with an URL such as `https://uk.wikipedia.org/wiki/.cn`, YaCy current crawler implementation thinks `.cn` is the file extension, and tries to find a parser capable to process it. But no one is found, so the URL is stacked on the "NOLOAD" stack, which means that the URL is indexed, but the content is not loaded nor parsed. You can check the metadata for this URL in your Solr index, and you will see it contains only a pseudo response.

A more proper solution will probably to check also the `Content-Type' earlier, but this modifies a bit the indexing workflow...

**Comment by Vort** [comment]
It is better also to check actual file contents.
For example, in [this](http://newsimg.bbc.co.uk/media/images/67373000/jpg/_67373987_09f1654a-e583-4b5f-bfc4-f05850c6d3ce.jpg) link both extension (```.jpg```) and content-type (```image/jpeg```) are wrong. It is actually ```.bmp``` image.
And this is not a rare problem: even [manual](https://mimesniff.spec.whatwg.org/#determining-the-computed-mime-type-of-a-resource) exists on how to handle it.

**Comment by luccioman** [comment]
@Vort if you want to have a look, with commit fcf6b16 there is now a new "Media Type detection" section in the advanced crawl start page, that let you choose to always cross check file extensions against actual Media Type. For now still relying on Content-Type header, but at least this fixes many URLs that were previously not properly parsed, notably the one in your screenshot.

**Comment by Vort** [comment]
Looks like at some time more proper handling should be introduced, but for now such solution is sufficient, thanks.
This issue is done, maybe similar one should be opened in future.
