### ISSUE TITLE
NetworkHistory fails to update automatically

### ISSUE THREAD

**Issue by Vort** [yacy/yacy_search_server#251]
With DHT-in transfer enabled, URL count of node is constantly growing.
That was correctly reflected by [NetworkHistory.png](http://localhost:8090/NetworkHistory.png?columns=cI&scale=1&maxtime=24&width=660) chart.
But since some update, values of this chart stand still:
![networkhistory](https://user-images.githubusercontent.com/1242858/48143091-c31a3500-e2b6-11e8-8150-a5f1877d6432.png)
Unless server is restarted or [HostBrowser.html](http://localhost:8090/HostBrowser.html?admin=true&hosts=) is visited.
It would be great to return autoupdate functionality for it.

**Comment by luccioman** [comment]
@Vort each time the HostBrowser.html page is visited by an authenticated user, an explicit commit is done on the Solr index, whereas no explicit commit is done when statistics used by the NetworkHistory chart are computed.

So it looks like this regression dates back to the upgrade from Solr 5.5 to Solr 6.6 (see commit 6fe7359) : the default Solr configuration has been updated and autocommit is still enabled, but because the [openSearcher](https://github.com/yacy/yacy_search_server/blob/6fe735945da97abcbb91ac545fb11cff9d48effc/defaults/solr/solrconfig.xml#L304) property has been set to false and because soft auto commit is indeed disabled (its maxTime property is defaulted to -1), auto-committed documents are no more made visible to the application.

Maybe @Orbiter would confirm there was some good reason (other than applying new Solr configuration example [defaults](https://github.com/apache/lucene-solr/blob/releases/lucene-solr/6.6.0/solr/example/files/conf/solrconfig.xml#L304)) to set that `openSearcher` property to false? Otherwise I think that we should revert it to true.

**Comment by luccioman** [comment]
Another possible fix would be to enable soft auto commits, as proposed in PR #157. But the proposed commit interval of 1 second still looks like a bit short to me. I will try to take some measurement of performances impacts of both solutions. 
If anyone wants to do the same with his/her own peer, results are welcome.

**Comment by luccioman** [comment]
On a MS Windows 10 machine, with a Oracle JDK 1.8_0_192, 1024 Mb memory dedicated to the JVM and a SSD disk, I launched and monitored with VisualVM the following test cases:
- intranet mode, empty index, crawl of roughly 2000 files
- webportal mode, empty index, import of wikimedia dump with roughly 61000 articles
- p2p mode, index with roughly 1 million documents, crawl of 1000 pages

Each test case was launched with :
- the current YaCy default Solr config
- hard autocommit with `openSearcher` property set to true
- soft autocommit with `maxTime` property set to 5s, 1s and 10ms

In all cases the instant CPU usage and memory usage are rather equivalent, except with the soft autocommit maxTime of 10ms which adds around a 10% CPU usage overhead.
The total processing time is similar between hard autocommit with `openSearcher` property set to true and soft autocommits, both adding between 5 to 10% to the total time depending on the test case.

**Comment by luccioman** [comment]
@Vort if you wish to test the fix of this issue, the default Solr config has been updated on the master branch.

**Comment by Vort** [comment]
Now chart is updated properly. Thank you.
![yacch](https://user-images.githubusercontent.com/1242858/48727470-f788dc00-ec3a-11e8-8819-18618f8d7389.png)
