### ISSUE TITLE
WIKI is Down

### ISSUE THREAD

**Issue by webdawg** [yacy/yacy_search_server#253]
Wiki seems to be offline.  What version of java should I use?

**Comment by webdawg** [comment]
I used this as a guide for install:  https://hub.docker.com/r/luccioman/yacy/~/dockerfile/

**Comment by luccioman** [comment]
Hello @webdawg,  your issue title is rather misleading... Anyway if your question is which Java version should be used to run YaCy : latest Java 1.8 is a good choice as it can run both the YaCy 1.92/9000 release (a bit old now) and more recent upgrades or latest sources.
Contrary to that, JDK 11 is safe to run only from latest YaCy sources because of issue #241.

**Comment by Starkmann** [comment]
Misleading or not, but the wiki is really down since a couple of days. ;-(
https://wiki.yacy.net/

**Comment by virtadpt** [comment]
The wiki really is down - nothing's being returned by the web server.  Could somebody please look in on it?

**Comment by Orbiter** [comment]
Well it's up again, the problem was caused by a php version switch. However, we still have a database problem which prevents editing. I'm working on that.

**Comment by kotenok2000** [comment]
If i connect to https://wiki.yacy.net i get
"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@wiki.yacy.net to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log."
But if i connect to https://wiki.yacy.net/index.php/Hauptseite everything works
