### ISSUE TITLE
Unable to change memory limits on yacy-search snap

### ISSUE THREAD

**Issue by diddledan** [yacy/yacy_search_server#269]
I've installed and tested yacy-search as a snap but am hitting memory limit issues. I tried raising the limit but it seems that the startup script is ignoring the settings in favour of the default values (600MB).

Looking at the startup script `yacy/startYACY.sh` it appears that it tries to load the `$CONFIGFILE` from a relative path `DATA/SETTINGS/yacy.conf`, the parent of which is set by ```cd "`dirname $0`"```. As `$0` references the startup script and this is inside the snap the relative path does not exist. The snap-specific preload script `yacy/addon/snap/snapStartYACY.sh` appears to believe it can set the data path but this overridden path is not used when setting the memory limits in the startup script.

---

Like @popey who reported #254 I work with snaps, though as a community contributor not sponsored/employed by Canonical where Popey is.

**Comment by luccioman** [comment]
Thank you @diddledan for reporting this.

This was indeed the `startYACY.sh` script that did not read the configuration file at the proper path when explicitly passing a custom data path with `-s` or `-g` option, as done in the snap package.

The fix is published on the yacy-search snap, so you can refresh and check it.
