### ISSUE TITLE
Please add a option for unauthenticated users in Remote results resorting for better experience.

### ISSUE THREAD

**Issue by tangdou1** [yacy/yacy_search_server#291]
Remote results resorting
1. On demand, server-side 
2. Automated, with JavaScript in the browser for authenticated users only. 
3. Automated, with JavaScript in the browser for unauthenticated users. (Please add this option)

**Comment by luccioman** [comment]
@tangdou1 the JavaScript resorting mode is currently not enabled for unauthenticated users because it can easily drive a very high server load. 
If we want this option, I suggest to add a customizable limit on the number of unauthenticated JavaScript resorted search requests (per minute for example).

**Comment by tangdou1** [comment]
> 
> 
> @tangdou1 the JavaScript resorting mode is currently not enabled for unauthenticated users because it can easily drive a very high server load.
> If we want this option, I suggest to add a customizable limit on the number of unauthenticated JavaScript resorted search requests (per minute for example).

That is a good idea! Because I want others to enjoy the test of yacy search when thers is a `Automated, with JavaScript in the browser for unauthenticated users` option.

**Comment by tangdou1** [comment]
thanks
