### ISSUE TITLE
How to configure YaCy Search Client using bootstrapcss?

### ISSUE THREAD

**Issue by rafaelrdealmeida** [yacy/yacy_search_server#310]
Yacy is installed and indexing files perfectly. However, I can't open the files either on localhost or on the outside.

I am currently indexing the intranet (file:///...)

I believe the solution to this is here: https://github.com/winnerineast/yacy_webclient_bootstrap

However, after cloning "yacy_webclient_bootstrap" into the "yacy" folder what do I need to do to make it work?

I would like to be able to open the files on localhost and outside

best

**Comment by Orbiter** [comment]
This challenge has no connection to the bootstrap webclient, because files indexed with the file:// protocol can naturally only be opened on the same host where the index is created.

If you want to make it possible that these files are accessible from outside of your host, you must *host* them, i.e. put them on a ftp or smb server and then re-index them with the correct url; smb:// or ftp:// protocol
