### ISSUE TITLE
JSON-Evil license [open source compliance]

### ISSUE THREAD

**Issue by onlyjob** [yacy/yacy_search_server#347]
The following files are licensed under non-free JSON-Evil license which is not Open Source compliant:

    htroot/api/trail_p.java
    htroot/cytag.java
    source/net/yacy/cora/util/JSONArray.java
    source/net/yacy/cora/util/JSONException.java
    source/net/yacy/cora/util/JSONObject.java
    source/net/yacy/cora/util/JSONString.java
    source/net/yacy/cora/util/JSONTokener.java

See the following page for details: https://wiki.debian.org/qa.debian.org/jsonevil

**Comment by onlyjob** [comment]
`org.json.*` is almost a drop-in replacement from https://android.googlesource.com/platform/libcore

(Available in Debian as "_libandroid-json-java_" package that provides `/usr/share/java/com.android.json.jar`).

**Comment by Orbiter** [comment]
interesting, I was not aware that the line makes the license non-free.
For trail_p.java and cytag.java I removed the line in https://github.com/yacy/yacy_search_server/commit/0a7bda2a2164978c2a9a1e051652cb5b95432705
I can do this because I made these files and possibly copied the lines beeing unaware that the line is harmfull. As both files are my own work, I can do this in a way of re-licensing.

For the org.json.* library I have to do further planning.

**Comment by Orbiter** [comment]
One aspect about my local code clone of org.json.* was, that I made a very tiny code change (usage of LinkedHashMap instead of HashMap to fix the order of objects - that makes them prettier to read) which I tried to get used in upstream (pull request failed).

So I would prefer to be able to make the same change in an replacement. I must see which one is approriate for that.

**Comment by onlyjob** [comment]
Thanks. For the sake of best practice it is best not to fork any libraries (and clearly mark modifications if you absolutely must fork) to avoid maintenance burden. Ideally it is the best to use well maintained libraries. "gson" is another alternative (libgoogle-gson-java)...

FYI `org.json.*` from android is a rewrite of the original evil-licensed JSON implementation that you've forked...

**Comment by onlyjob** [comment]
Awesome, thank you.
