### ISSUE TITLE
Is there a way to do direct injects of data from metasearch engines?

### ISSUE THREAD

**Issue by Outstep** [yacy/yacy_search_server#351]
Hello,

I really like YaCy and am wanted to expand upon it capabilities if possible.

First, for some reason the YaCy Forum does not reset my password so I cannot post there.

I would like to take some website data that I get from another metasearch engine (i.e. SearX, etc..) and direct inject the results without YaCy having to crawl the websites that are injected so that they can be used for the next "similar" YaCy query.

How can I go about doing some direct injects of the data?
Cheers and stay safe

**Comment by Orbiter** [comment]
Hey Outstep,

the forum is now at https://searchlab.eu/

Taking search results from other search engines means that you have to scrape them, then feed the result in YaCy.

**Comment by Outstep** [comment]
Hi Michael,

I tried the forum at the address you gave and it says that it found my email and was going to send me a link to update the password, but I do not get any email and cannot reset my password.

Regarding the YaCy Inject, there are a number of ways to get results which could be from external search engine API calls, scraping, funded queries, external crawlers, etc...

I would like to be able to inject the data that I will have from many sources into my YaCy local nodes. On that note, I plan to start up a few nodes just for this purpose so that they can get results from many different sources.

The result will be that external sources (search engines and metasearch engines, etc.) will be able supply more links to the nodes that I will have running but that also the rest of the active YaCy P2P network will be able to see, and utilize those links as well.

Am currently trying to look into what it would take to be able to support injects and maybe even make a fork of YaCy to make some changes for this purpose.

Cheers

**Comment by onlyjob** [comment]
IMHO YaCy is superior to SearX precisely because YaCy is not a meta search but a genuine crawler. 

These days one of the major problems with search is centralisation and monopolisation that is abused to censor important information. If you get your search results from Google, indirectly through SearX or other metasearch system, then you won't see what Google wants to hide from you.

The very concept of YaCy's distributed community crawlers addresses serious problem of bias in major search engines.
Instead of inflating and diluting YaCy's indexes with data from metasearch engines I recommend to spend more effort for crawling relevant web sites to produce original indexes rather than derivatives of the existing search monopolists.

**Comment by Orbiter** [comment]
right, scraping the web and indexing is the core function of YaCy, not taking content from other search engines. People might do it, but thats outside the focus of the project.

**Comment by lonnietc** [comment]
Hello,

I was wondering about injects as well but see that the better approach is not to do that but have YaCy crawl the sites itself.

With that in mind, can you please help me with some type of REST example that can be used to send a single, or better yet a list of websites for a local YaCy node queue up to crawl?

In this way, YaCy I can send websites of interest to my local YaCy node to be crawled and once completed then the whole YaCy community can benefit from the results stored in the distributed database.

Any information that you could provide would be greatly appreciated.
