### ISSUE TITLE
miscalculated number of search results?

### ISSUE THREAD

**Issue by onlyjob** [yacy/yacy_search_server#359]
I've searched for a specific phrase on YaCy and got the following: `1-1 of 86 ; (69 local, 17 remote from 4 YaCy peers)`. However only _one_ document is shown.

That might be fair -- local node have a porn blacklist so some of the results may have been filtered (I'm guessing). But showing _total_ number of search results to user when only a small fraction of those results are actually presented is misleading. What is the point of "we have more links that we are not showing to you"?

IMHO filtered results should be removed from totals calculation.

**Comment by frankenstein91** [comment]
If the peer is connected to the P2P network, it could also be that not all results have arrived yet.
Have you tried the search again after some minutes?

**Comment by onlyjob** [comment]
Yes, I have been trying for a while over dozen times and was consistently getting more _total_ documents count than what was actually found/shown. it is a reproducible problem.

**Comment by Orbiter** [comment]
This won't fix and Google has the same problem.
The reason is that it is not possible to make an proposition against the whole index because there might be numerous reasons why search results cannot be shown. But this evaluation is only done for the number of document that are shown, never for the whole index set.
