### ISSUE TITLE
What is "Limit Crawler"?

### ISSUE THREAD

**Issue by onlyjob** [yacy/yacy_search_server#361]
Please document.

**Comment by aleksejrs** [comment]
https://wiki.yacy.net/index.php/De:WatchCrawler#Pufferkennzahlen (https://web.archive.org/web/20200722131001/https://wiki.yacy.net/index.php/De:WatchCrawler) says the following about it, which I do not understand:

    Indexieren - Heruntergeladene Seiten, die darauf warten indexiert zu werden.
    Lader - URLs, die darauf warten heruntergeladen zu werden.
    Lokaler Crawler - Seiten, die darauf warten vom eigenen Crawler bearbeitet zu werden.
    Limit Crawler - Seiten, die darauf warten von einem Crawler auf einem beliebigen YaCy Peer bearbeitet zu werden.
    Remote Crawler - Seiten, die darauf warten durch den eigenen Crawler für einen Crawler auf einem entfernten YaCy Peer bearbeitet zu werden.

**Comment by songproducer** [comment]
I don't know but here is a straight Google translate:

> Indexing - Downloaded pages waiting to be indexed.
> Loader - URLs waiting to be downloaded.
> Local crawler - pages that are waiting to be processed by their own crawler.
> Limit Crawler - Pages waiting to be processed by a crawler on any YaCy peer.
> Remote Crawler - Pages that are waiting to be processed by their own crawler for a crawler on a remote YaCy peer.

**Comment by Orbiter** [comment]
Well that is not so easy. In YaCy we want that we are able to do de-centralized crawls. That requires that parts of a crawl are assigned to remote peers. To do this correctly the remote crawl must not do double-work, that means somewhere a double-check for already found URLs for one crawl must be done. One single URL can be referred by several other pages, so those doubles must be removed.

In a distributed environment a double-check cannot be made because it would require a central database, something that we don't want. So here is the solution: the peer which initiate the remote crawl creates a full crawl tree and identifies which urls are at the leaves of that tree. Those leaves are not touched (loaded) by the crawling peer but assigned to a stack where remote peers can pull off urls from that stack. URLs from that stack are called the "limit stack" and the process that controls that urls are stacked there and processed is called the "limit crawler".

On the other side - the remote peers who fetch urls from that limit stack - control their crawl process of other-peer-limit-urls with the "remote crawler" process.
