### ISSUE TITLE
How to install (on Windows) for all users?

### ISSUE THREAD

**Issue by teknowledgist** [yacy/yacy_search_server#367]
YaCy installs within the installing user's profile.  Is there any way to have it be a "machine" or "system" install?  Some NSIS installers have an `/allusers` switch for this.

Thanks.

**Comment by frankenstein91** [comment]
This is, I think, a question of how it should be implemented. My suggestion would be to let Yacy start automatically as a Windows service. After that it would be possible for every user to use the web interface. Yacy is an application that is only operated via the browser. 
Or should every user have his own data directory and thus his own Yacy Node? I would only see an advantage here for training purposes.

**Comment by teknowledgist** [comment]
I can see an argument for both.  A service with shared index makes YaCy available to everyone (including non-local users) without a user logged in.  Personal data directories make it more private.  Maybe it could be an installer option to choose the mode?

**Comment by frankenstein91** [comment]
The software is more of a web search. It is thought of the task area rather in the direction of MetaGer. The local search and the SMB search have been added for projects, but the focus is on data which is public for all participants.

**Comment by teknowledgist** [comment]
So that's a stronger argument for a machine install with a service.  If it installs for the user, it only runs when the user is logged in.

**Comment by frankenstein91** [comment]
> If it installs for the user, it only runs when the user is logged in.

If you work with different ports per user and distribute the different Yacy instances to services that log on as users, this limitation would not exist. For this, the security concept of Windows would have to be softened a bit and the user would have to be given the right to log on as a service. How the performance on the system is with several Yacy services on the same hardware, I unfortunately can not evaluate. I still wouldn't advise it, though.

I just realized that I misread your argument/question the other day. I don't know why I think all the time that you want to use several yacys on one system. Probably because it's the case with normal software like Office. You install the software once and then you can use them all.
So now I would like to give you the installation suggestion for Windows, which corresponds more to your question. 

First you should create a new user on your target system. I always call such users AplAdmin or Appl_AddSoftwareHere. Then you log in as this user and install Yacy. Then you create a Windows service for Yacy. In the MMC, you enter the login data for the newly created user. Now Yacy should start with the system under a different user than you use for your purposes. The advantage, you can protect your data better with the Windows access rights. Since Yacy is controlled via the web interface, anyone can now use Yacy on the system. If not everyone on the local system should be a Yacy Admin, you have to change one more setting here. By default, everyone on localhost is logged in as admin.
I hope this answer helps you and fits better to your question.

**Comment by teknowledgist** [comment]
Thank you for the suggestions.  I realize there are probably ways to work around the per-user install, but I still think having a machine install (as a service) option is a better choice.  Certainly more "standard" in the Windows world and much easier if YaCy is going to be deployed.  

Actually, I just tried installing YaCy as `SYSTEM`.  It took a while to find, but it ended up in "C:\Windows\SysWOW64\config\systemprofile\YaCy".  Running the `startYACY.bat` did not give any errors, but I cannot access the web interface.

**Comment by reger24** [comment]
run installYaCyWindowsService.bat  in the YaCy directory to install it as service.
