### ISSUE TITLE
add gradle build process, remove ant

### ISSUE THREAD

**Issue by Orbiter** [yacy/yacy_search_server#377]
A lot of libraries should be upgraded, but I do not want to bloat the jar libraries inside this repository any more.
The best step would be to ditch the ant build process and start new with gradle.

This is (also) a call for gradle hackers who are experienced with building of Windows/Mac-native applications.

**Comment by sixcooler** [comment]
I already startet on freshing libs. (will go on, whenever I've some time)
Why to prefer gradle over maven?

**Comment by yacylover** [comment]
Hi,

 


Great!

It would be great, too if this bug can be fixed in one of the next releases:

https://github.com/yacy/yacy_search_server/issues/372

It is still present in actual builds 1.922/100*

 

 

Best

 

LA_FORGE

Am 19.08.2020 um 12:06 schrieb sixcooler:

**Comment by Orbiter** [comment]
@sixcooler the main purpose of this is to get away from libraries in the repository. So maven/gradle is both on the right side of a solution. However I consider maven a bit outdated since xml is a bit outdated.

**Comment by reger24** [comment]
> A lot of libraries should be upgraded, but I do not want to bloat the jar libraries inside this repository any more. The best step would be to ditch the ant build process and start new with gradle.
> 
> This is (also) a call for gradle hackers who are experienced with building of Windows/Mac-native applications.

Right now the Gradle script is a joke - the old Maven at least worked w/o ant (except the htroot additional source path w/o package structure etc.). But I hear you - Gradle it is.

Me not beeing a Gradle hacker but I guess I can at least do some stuff to support the migration from Ant to Gradle.
So I'll start and after 80-90% is migrated we can decide if we do things different if Gradle build it requires.

No reply expected... I'll start as long as I've some spare time.

**Comment by reger24** [comment]
with commit https://github.com/yacy/yacy_search_server/commit/6dcb58a4b59ef4f0aadc92858c8bf7c7c322e826
all needed legacy Ant tasks are available in Gradle build

List of Ant targets (with result comment)
- "readBuildProperties" = see no use
- "init" = not needed (ant internal prop initialization)
- "javadoc" = gradle-task javadoc
- "compile-core" = gradle-task build
- "compile-htroot" = gradle-task compileHtrootServlets
- "compile" = gradle-task build
- "all" = gradle-task build
- "copyMain4Dist" = gradle-task packageDist
- "compileTest" = gradle-task compileTestJava (std)
- "test" = gradle-task test (std)
- "dist" = gradle-task packageDist
- "portalsearch" = gradle-task packagePortalsearch (is that file still used?)
- "clean" = gradle-task clean (std)
- "run" = gradle-task run (std) or shell
- "run-single" = not needed (old stuff)
- "debug" = won't gradleize ide or run
- "stop" = just a shell script
- "create-doc" = gradle-task javadoc
- "distWinInstaller" = won't impl. external tool needed
- "distMacApp" = won't impl. external tool needed
- "deleteData" = hm, won't impl. use nomale system

**Comment by Orbiter** [comment]
Wow, great!

**Comment by reger24** [comment]
@Orbiter  thank's 
.... I leave it up to you, when to delete the (old) build.xml

**Comment by Orbiter** [comment]
I have recently installed openjdk 16.0.2 and since then I run into problems with all gradle projects.
- gradle below 7.0 fail with `Unsupported class file major version 60`
- the gradle version in the commited gradlew is 6.9 and upgrading to 7.3 creates a strange `Entry yacycore-1.925/lib/yacycore.jar is a duplicate but no duplicate handling strategy has been set.`

So the obvious solution would be a migration to gradle >= 7.3 .. to support also jdk 17 https://docs.gradle.org/7.3/release-notes.html#java17

**Comment by reger24** [comment]
I'd similar class file version issue at the beginning with using Gradle 6.9 (coming from 7.3) my error was an other version number (think 52 or so), fix was (if I remember right) to set the correct and SAME JDK version for everything

anyway ... don't like/want stay with 6.9 forever ..... and on my side Gradle 7.3.3 works fine
The mentioned duplicate error ist fixed by ) ( https://github.com/yacy/yacy_search_server/commit/68e5c413850b51328feca6f9e74b1f8aea809ce6 ) 

By the way the build-in distTar and distZip have a predefined directory layout with /lib and /bin,
so the /lib directory fit's by accident to our old structure
in the /bin is a yacycore (sh script) and yacycore.bat  automatically include and intended to start YaCy
result on my Win 
   - The input line is too long.
   - The syntax of the command is incorrect.
With other words - they don't work with the full classpath (the startYaCy by accident does)

So in the moment we've 2 distributions .... the default (distZip, distTart which not completely work)
and the legacy archive with the old/known naming convention ( yacy_v1.925_20220125_10198.tar.gz / yacy_v1.925_20220125_10198.zip )
At one day it needs to be decided which one should survive !

**Comment by Orbiter** [comment]
ok, I am really happy with this, I believe that was a lot of work.

About the release naming convention: well we should overthing this, obviosly making a version number out of `number-of-commits plus 9000` is strange. There was once a reason for that, the migration from svn, but we should move forward somehow.

Another point: I recently made my first "nix-file" for nixos. That thing requires a version number which is identical with a git tag. So that must be taken into account.

To finalize this, we must test all release options. For example: the dockerfile, which depends on ant.

**Comment by henschi** [comment]
@Orbiter @reger24 

What is the current status?

I could offer to try a Maven integration/migration.

**Comment by okybaca** [comment]
> I could offer to try a Maven integration/migration.

that would be great!

friend of mine, java developer, wanted to help a bit with the code, but
missed some debugging environment he was used to, either maven or graddle. 

would it be possible to not "migrate", but keep both processes as alternatives?
(since @orbiter needs ant for docker etc.)

graddle was used before, and possibly could be excavated by reverting
commits like: 
https://github.com/yacy/yacy_search_server/commit/4503b9e292f2a2f4aa9c5ff9538b7a75231f81c9

maven would be fine as well!

as you can see, there is sort of lack of progress in the developement, so
anything you do is a step forward. if ant is kept, there is probably no
question in adding maven support, imho.

**Comment by henschi** [comment]
Sorry for deleting my post.

I think Maven is the default build tool for Java development.
It is possible to add a parallel Maven build file, but it is double the effort for the maintenance.
We could clarify with Orbiter why it needs Ant for Docker.

I will submit a few PRs in the next few days to replace old libs and remove a few CVEs, since Yacy is directly accessible from the Internet.
After that I will try to create a Maven Pom next to it.

**Comment by reger24** [comment]
> Sorry for deleting my post.
> 
> I think Maven is the default build tool for Java development.

I sugest check with Orbiter, as the old maven build was never adopted as main build script and the use of Gradle was skipped  in favour to stay with ant becaus of better support of Linux, Docker etc.

**Comment by henschi** [comment]
I understand.

I will first create a Maven POM with which you can “only” develop Java. This can be done in parallel with Ant.
But unfortunately there are currently Eclipse project files in the GIT that speak against the use of Maven. We might have to clarify whether these files could be removed in the future.

**Comment by okybaca** [comment]
Sat, Mar 29, 2025 at 03:38:00AM -0700, Henschi pise:
> henschi left a comment (yacy/yacy_search_server#377)
> I will first create a Maven POM with which you can “only” develop Java. 
> This can be done in parallel with Ant.

I absolutely agree. 

> But unfortunately there are currently Eclipse project files in the GIT
> that speak against the use of Maven.  We might have to clarify whether
> these files could be removed in the future.

Yes, let's leave that for future discussion.

**Comment by reger24** [comment]
> I see.
> 
> I will first create a Maven POM with which you can “only” develop Java. This can be done in parallel with Ant. 

Maybe you can reuse some stuff from old pom
https://github.com/yacy/yacy_search_server/blob/3befaaf4f1bcff637b1faa2845c9615ebb934411/pom.xml

**Comment by henschi** [comment]
@reger24 

I don't understand the hint with the automatic compilation of htroot.
I find a corresponding javac block in the former Maven POM, but what should it do? In the current release file I only find a copy of the files from the htroot directory. I can't find anything compiled there. Am I missing something?

**Comment by henschi** [comment]
@reger24 

Ah, I've found it. Back then there were a few Java classes in htdocs. Orbiter has already rebuilt many things so that it is now much easier with Maven.
