### ISSUE TITLE
 Can you fix network graph at http://localhost:8090/Network.html to stop it from flashing?

### ISSUE THREAD

**Issue by kotenok2000** [yacy/yacy_search_server#428]
Can you fix network graph at http://localhost:8090/Network.html to stop it from flashing?
https://user-images.githubusercontent.com/8822292/143665375-b8e96098-2bf2-4d81-895f-dbd4c261dc15.mp4

**Comment by Orbiter** [comment]
what flashing?

**Comment by kotenok2000** [comment]
Perhaps i was too vague.
I want yacy to show timestamped frames sequentially and to not flash older data.

**Comment by thkoch2001** [comment]
Thank you for the video, but I still don't understand what this request is about.

**Comment by kotenok2000** [comment]
Make it so time in upper right corner of the graph does not change randomly.

**Comment by kotenok2000** [comment]
https://user-images.githubusercontent.com/8822292/162574811-d26e2c89-d265-4b42-a6b9-d8fbaf0ae0e5.mp4

**Comment by Orbiter** [comment]
oh, yes, that happens because of the concept of the animation:

- the animation consists of 6 images that are presented in a loop constantly
- after several seconds only one of these images is replaced by a new one
- this "rotates" new images into the loop
- the loop of the six images produce animations that you want and see: waves around peers and points traveling along the edges of the lines between peer and peer name
- that creates flashing of new appearing peers: first slow because only one image is replaced, then changing in on/off time because more and more images of the loop is replaced.
- the flashing of the date is not wanted, but an effect that cannot be suppressed.

So overall, this works as designed!
