### ISSUE TITLE
Using YaCy a little, I found such problems

### ISSUE THREAD

**Issue by Barmarel** [yacy/yacy_search_server#433]
### Using YaCy for a bit, I found these problems:

1.  Built-in skins apply only to the page for selecting skins. The other pages always use the most standard skin.

2.  It is impossible to apply a password to the standard administrator account. After a password is specified and I press enter button, password fields become empty and nothing happens, I can use YaCy admin part as before without entering a password.

3.  The interface for mobile screens is very poorly adapted.

4.  When using a language other than English, some elements are poorly displayed - words go out of margins, elements overlap each other, etc.

______________________
_Translated with DeepL._

**Comment by Orbiter** [comment]
1 - no it actually works. What you see is an effect caused by your browser caching the old style. Only the skin-edit page disables usage of the browser cache.
2 - probably same effect
3 - true! It is not made for this, it never was. YaCy was written mostly in the late 00 years, a time where not even mobile web browsers existed!
4 - true as well, we need support from users in those languages. We are not a company, the code consists only of work from volunteers. That means in your case that you are welcome to become a volunteer!
