### ISSUE TITLE
Yacy search server vs yacy grid

### ISSUE THREAD

**Issue by ilyakooo0** [yacy/yacy_search_server#456]
I couldn't find information regarding what is the "recommended" YaCy installation. I found github issues that state that this repo is a "legacy" version of YaCy and YaCy grid is the new version, but I couldn't find any information regarding YaCy grid on the YaCy website.

I want to understand if YaCy grid is ready to use, or is it recommended to the version of yacy from this repo. Is the YaCy grid network larger/more active? Is it even a separate network? 

I would really appreciate any information that could clarify the current state of things (:

**Comment by Orbiter** [comment]
YaCy Grid is in production since five years for selected users who get consulting from me.
The public documentation and usage schema is now growing under the name "YaCy Searchlab" and the corresponding web page is https://searchlab.eu

More details are also here: https://community.searchlab.eu/t/the-searchlab-project/867/7

**Comment by ilyakooo0** [comment]
So, yacy grid is not a direct competitor to legacy yacy in the sense that legacy yacy is primarily a decentralized search engine, while yacy grid is primarily a centralized search engine with partial backward compatibility for P2P?

**Comment by ilyakooo0** [comment]
Thanks! This really clears things up!
