### ISSUE TITLE
Old documentation wiki (from Readme link) not full functional

### ISSUE THREAD

**Issue by reger24** [yacy/yacy_search_server#458]
- no login possible (Internal Server Error - Apache Server at wiki.yacy.net Port 443)
- accessing any special page (same error as above)

making any update impossible (for both)
- https://wiki.yacy.net/index.php/De:Start
- https://wiki.yacy.net/index.php/En:Start

@Orbiter should old wiki still be used or is your intention to use the gibhub wiki feature for future documentation ?

**Comment by Orbiter** [comment]
I would prefer to put new documentation right on the YaCy home page, so there is no other place.
The old wiki is broken and all my rescue attempts have failed. Github wiki is not an option because that would be too unusal.

Editing the YaCy home page is possible for everyone just by placing a pull request to any page at https://github.com/yacy/yacy_net_homepage/tree/master/docs

The web page builds itself and will be published automatically after a commit or a merge.
Furthermore editing at github itself is very convenient because its markdown and github has a markdown.

I also already have started to fetch information from the wiki and put it to that place which you can find at
https://github.com/yacy/yacy_net_homepage/tree/master/docs/api
https://github.com/yacy/yacy_net_homepage/tree/master/docs/operation

However that is far from beeing complete.
