### ISSUE TITLE
Version numbering problem

### ISSUE THREAD

**Issue by sebastianmbobrecki** [yacy/yacy_search_server#459]
Hi,

All recent builds from git with gradlew have version number 1.925/10210. I also see that from the same `./gradlew packageDist` build I get two files with different version number, e.g. from few minutes ago:"
`yacy_search_server/build/distributions/yacy_v1.925_20220208_10250.tar.gz`
and :
`yacy_search_server/build/distributions/legacyDistFiles/yacy_v1.925_20220211_10264.tar.gz`
Am I doing something wrong, misunderstood something or it's a bug?

**Comment by sebastianmbobrecki** [comment]
I made fresh `git clone` and it seems like it resolved problem with archive files. Unfortunately the version number still stuck at 1.925/10210 when built with:
```
$ ./gradlew build
$ ./gradlew packageDist
```
But when I built it old way with ant on the same tree:
```
$ ant clean all dist
```
version number visible in YaCy is updated to 1.925/10264 like it should.

**Comment by reger24** [comment]
Can't reproduce ..... 
as mentioned the gitbuildnumber.properties is updated AFTER first build (by libbuild/GitComInf-1.0-all.jar - the reason for the AFTER is that build would otherwise fail if not git clone)

so if you do a 2nd build (gradlew build) - also the displayed version MUST be current.
If you want to be 100% sure you could do 
1. "gradlew storeGitComInf" - to get commit count update from git repo before 1st build
2. "gradlew build
In any case in all my testings described issue with the revision number is only possible on very 1st build or not a git clone.

**Comment by sebastianmbobrecki** [comment]
So `./gradlew storeGitComInf` have to be done after `git clone` and every subsequent `git pull`? Do I also have to do `./gradlew clean` after each pull and before `./gradlew storeGitComInf`? If so, it should be mentioned in README.md.

P.S. It's also interesting that this problem never show up with plain ant build. Maybe this step should be added to `./gradlew build`.

**Comment by reger24** [comment]
no, no clean needed.... and also the gradlew storeGitComInf would be beneficial only on the very first build, because if you issue a build - storeGitComInf is automatically appended to the commands.

Explanation:
The reason for the possible version number problem after the gradle conversion is, as yacy uses a special version number and relays on it in the old ant and maven builds, special ant and maven plugins were used.
Gradle relays on the output of the workaround with the external libbuild/GitComInf-1.0-all.jar (as no-one intends to create again a gradle plugin for this version number topic)

But as GitComInf-1.0-all.jar is external, if anything goes wrong, build will fail - so finally it was not include it in the nomal lifecycle (before javaCompile) but with a trick after the build, to make 100% sure even if this buildnumer topic or the property file is missing..... to be at least able to compile for people e.g. not cloning from git or having trouble with GitComInf-1.0-all.jar

The only donwside as you experienced..... may be the very first build uses es older revision number
