### ISSUE TITLE
Maven custom plugins

### ISSUE THREAD

**Issue by tglman** [yacy/yacy_search_server#57]
I tryed to build the project straight with maven and i got some error because i didn't have a yacy specific plugin, digging in the pom i saw that you are using your custom plugin to get the git revision, but luckely the last version of the buildnumber official plugin can do that, here the reference:

```
<groupId>org.codehaus.mojo</groupId>
<artifactId>buildnumber-maven-plugin</artifactId>
```

http://www.mojohaus.org/buildnumber-maven-plugin/create-mojo.html

i can help you to configure it if is needed ;)

**Comment by reger24** [comment]
At the time of creating the plugin, I've found no way to dupe the 9xxx build version counter.
Quick checking your proposal, it seems due to error _"Cannot run program "git" (in directory ....:CreateProcess error=2" the plugin relies on external installed git (so I gave up).
If you'd have a config solution (w/o external dependency) - it's appreciated.
cu

**Comment by reger24** [comment]
in the meantime we switched to Gradle and buildnumber is gathered by a supporting jar (not longer a plugin)
