### ISSUE TITLE
Push API

### ISSUE THREAD

**Issue by ceritium** [yacy/yacy_search_server#59]
I tried to use the Push API to submit my own scraped data to yacy but I am getting error 500 with GET and POST methods.

I found some documentation here: http://www.yacy-websuche.de/wiki/index.php/Dev:APIpush but the examples didn't work for me.

**Comment by luccioman** [comment]
Hi, example GET URL in wiki was deprecated regarding lastModified and contentType parameters. Instead of "&lastModified=value" and "&contentType=value" you now have to pass "&responseHeader-0=Last-Modified:value" and "&responseHeader-0=Content-Type:value". I just tested with latest dev YaCy version and this works fine.
I also updated wiki example URL.

**Comment by Orbiter** [comment]
closed regarding luccioman's retest
