### ISSUE TITLE
Ant dist error!

### ISSUE THREAD

**Issue by linkerlin** [yacy/yacy_search_server#94]
BUILD FAILED
/home/linker/gits/yacy/build.xml:470: Entry: yacy/libbuild/J7Zip-modified/target/classes/SevenZip/Compression/LZMA/Decoder$LiteralDecoder$Decoder2.class longer than 100characters.

**Comment by reger24** [comment]
happens after mixed use of Maven and Ant builds.
It goes away if you run maven clean:clean  on the libbuild/pom.xml   (which deletes the files ant doesn't need creating the error)
or use maven with release-profile to create a dist file, too.

P.S.
I don't think we should add something like this
        <exclude name="**/target/**" /> 
to the ant build.xml because ant shouldn't be worry about other build systems.

**Comment by sudheesh001** [comment]
I agree with the removal of `exclude`, in general we expect people to either use ant or maven. Is there a specific mixed usage case that could exist ? If not, we can safely remove the `<exclude name="**/target/**" />` and close this issue

**Comment by reger24** [comment]
No, I don't see any mixed intentional usage.
Most use likely ant (as that is the main supported build). The only mix is that maven uses a ant task to compile the htroot classes. By having ant as the main build the project is not really mavenized (e.g. having the parent pom in the libbuild directory instead of in top-level.
I don't expect that this will change shortly so both are independent with ant being the lead.

**Comment by luccioman** [comment]
Hello, we now have an example of intentional Ant/Maven mixed usage with [Travis](https://github.com/yacy/yacy_search_server/blob/a545523ab9fea60e498d9e63228945525667d7d4/.travis.yml) automated build. To my mind this mixed usage is useful to ensure everything is fine on a regular basis as long as both build systems are enabled on this project.

So for now I pragmatically [added](https://github.com/yacy/yacy_search_server/commit/27bd1921e4796459efce5fae4bd3214ba31d1ca3) the "**/target/**" Ant exclusion to make Travis build properly works.

I hope this is fine for you. Can we close this issue?
